---

- name: Make sure .pyenv directory exists
  file:
    path: "{{ pyenv_root }}"
    state: directory

- name: Make sure WORKON_HOME directory exists
  file:
    path: "{{ pyenv_virtualenvwrapper_home }}"
    state: directory
  when: pyenv_virtualenvwrapper

- name: Create .pyenvrc
  template:
    src: ".pyenvrc.j2"
    dest: "{{ pyenv_root }}/.pyenvrc"
    mode: "0644"

- name: Install Python interpreters
  shell: . {{ pyenv_root }}/.pyenvrc && pyenv install {{ item }}
  args:
    executable: "{{ pyenv_install_shell | default(omit) }}"
    creates: "{{ pyenv_root }}/versions/{{ item }}/bin/python"
  with_items: "{{ pyenv_python_versions }}"

- name: Get current global version
  shell: . {{ pyenv_root }}/.pyenvrc && pyenv global
  args:
    executable: "{{ pyenv_install_shell | default(omit) }}"
  register: pyenv_global_version
  changed_when: False

- name: Set pyenv global version
  shell: . {{ pyenv_root }}/.pyenvrc && pyenv global {{ pyenv_global }} && pyenv rehash
  args:
    executable: "{{ pyenv_install_shell | default(omit) }}"
  when: pyenv_global is defined and (pyenv_global_version.stdout_lines | join (" ")) != pyenv_global
