---
- name: Install pyenv build requirements
  become: true
  ansible.builtin.package:
    name: "{{ pyenv_build_requirements }}"
    state: present
    update_cache: true

- name: Install pyenv build requirements with Homebrew
  become: false
  homebrew:
    name: "{{ pyenv_build_requirements_with_homebrew }}"
  when: pyenv_homebrew_on_linux | bool

- name: Install with Git
  include_tasks: install_with_git.yml
  when: not pyenv_homebrew_on_linux | bool

- name: Install with Homebrew
  include_tasks: install_with_homebrew.yml
  when: pyenv_homebrew_on_linux | bool
