---
# tasks file for ansible-pyenv

- name: Load variables for the target system
  include_vars: "{{ item }}"
  with_first_found:
    - "{{ ansible_distribution }}.yml"
    - "{{ ansible_os_family }}.yml"
    - "default.yml"

- include: Linux.yml
  when: "ansible_system == 'Linux'"

- include: Darwin.yml
  when: "ansible_os_family == 'Darwin'"

- include: shell.yml
  when: pyenv_init_shell
