---

- name: Include Mojave variables
  include_vars: "os/Mojave.yml"

- name: Check if headers package exists
  stat:
    path: "{{ mojave_sdk_headers }}"
  register: mojave_sdk_headers_st

- name: Install package with expired Apple security certificates
  set_fact:
    mojave_sdk_headers_opts: "{% if pyenv_macos_untrusted_packages %}-allowUntrusted{% endif %}"

- name: Install macOS SDK headers for macOS 10.14
  become: true
  command: "installer -pkg {{ mojave_sdk_headers }} -target / {{ mojave_sdk_headers_opts }}"
  args:
    creates: /usr/include
  when: mojave_sdk_headers_st.stat.exists

- name: Use existing MACOSX_DEPLOYMENT_TARGET environment variable
  set_fact:
    macos_target: "{{ lookup('env', 'MACOSX_DEPLOYMENT_TARGET' )
                    | ternary (lookup('env', 'MACOSX_DEPLOYMENT_TARGET' ), macos_version) }}"

- name: Set MACOSX_DEPLOYMENT_TARGET environment variable
  set_fact:
    pyenv_install_environment: "{{ pyenv_install_environment
                                 | combine({ 'MACOSX_DEPLOYMENT_TARGET': macos_target }) }}"

- name: Use existing SDKROOT environment variable
  set_fact:
    sdkroot: "{{ lookup('env', 'SDKROOT' )
               | ternary (lookup('env', 'SDKROOT' ), omit) }}"

- name: Use xcrun to show the SDK path
  command: xcrun --sdk macosx --show-sdk-path
  register: xcrun_sdk_path
  ignore_errors: true
  changed_when: false

- name: Debug
  debug:
    var: xcrun_sdk_path

- name: Set SDKROOT to the SDK path returned by xcrun
  set_fact:
    sdkroot: "{{ xcrun_sdk_path.stdout | trim }}"
  when: xcrun_sdk_path.rc == 0 and xcrun_sdk_path.stdout

- name: Find macOS SDK headers and set SDKROOT
  when: sdkroot is undefined
  block:

    - name: Look for macOS SDK in Xcode
      stat:
        path: "/Applications/{{ item.app }}/{{ xcode_sdk_path }}/{{ item.sdk }}"
      with_items: "{{ xcode_sdk_lookup }}"
      register: xcode_sdk_st

    - name: Set path to macOS SDK in Xcode
      set_fact:
        sdkroot: "{{ item.stat.path }}"
      with_items: "{{ xcode_sdk_st.results }}"
      when:
        - item.stat.exists

    - name: Look for macOS SDK in Command Line Tools
      stat:
        path: "/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk"
      register: clt_sdk_st
      when: sdkroot is undefined

    - name: Set path to macOS SDK in Command Line Tools
      set_fact:
        sdkroot: "{{ clt_sdk_st.stat.path }}"
      when: sdkroot is undefined and clt_sdk_st.stat.exists

- name: Set SDKROOT environment variable
  set_fact:
    pyenv_install_environment: "{{ pyenv_install_environment
                                 | combine({ 'SDKROOT': sdkroot }) }}"
  when: sdkroot is defined
